FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/go-toolset:1.21 AS builder
ARG TARGETPLATFORM

ENV USER_UID=1001 \
    USER_NAME=assisted-installer

ENV COMPONENT_NAME=assisted-installer-agent
ENV COMPONENT_VERSION=1.0.0
ENV COMPONENT_TAG_EXTENSION=" "
ENV GOFLAGS="-p=4"
ENV GOEXPERIMENT=strictfipsruntime
ENV BUILD_TAGS="strictfipsruntime"

COPY --chown=${USER_UID} . /app
WORKDIR /app
RUN CGO_FLAG=1 make build


FROM --platform=$BUILDPLATFORM registry.access.redhat.com/ubi9/ubi-minimal:9.4

ENV USER_UID=0

RUN microdnf -y update && microdnf clean all

RUN subscription-manager repos --enable=codeready-builder-for-rhel-9-x86_64-rpms && \
    subscription-manager repos --enable=rhocp-4.17-for-rhel-9-x86_64-rpms

RUN PKGS="findutils iputils podman ipmitool file sg3_utils fio nmap dhclient tar openssh-clients chrony util-linux hwdata" && \
    X86_PKGS=$(if [ "$(uname -m)" == "x86_64" ]; then echo -n biosdevname dmidecode ; fi) && \
    ARM_PKGS=$(if [ "$(uname -m)" == "aarch64" ]; then echo -n dmidecode ; fi) && \
    PPC64LE_PKGS=$(if [ "$(uname -m)" == "ppc64le" ]; then echo -n '' ; fi) && \
    S390X_PKGS=$(if [ "$(uname -m)" == "s390x" ]; then echo -n '' ; fi) && \
    microdnf install -y $PKGS $X86_PKGS $ARM_PKGS $PPC64LE_PKGS $S390X_PKGS && \
    microdnf update -y systemd && \
    microdnf clean all && \
    rm -rf /var/cache/{yum,dnf,microdnf}/*

COPY --from=builder /app/build/agent /usr/bin/agent

# The step binaries are all symlinks to /usr/bin/agent
RUN ln -s /usr/bin/agent /usr/bin/free_addresses && \
    ln -s /usr/bin/agent /usr/bin/inventory && \
    ln -s /usr/bin/agent /usr/bin/logs_sender && \
    ln -s /usr/bin/agent /usr/bin/next_step_runner && \
    ln -s /usr/bin/agent /usr/bin/disk_speed_check

USER ${USER_UID}
